GET http://localhost:8080/accounts

###
POST http://localhost:8080/account
Content-Type: application/json

{"numberPhone": 1, "money": 1}
###
POST http://localhost:8080/account
Content-Type: application/json

{"numberPhone": 2, "money": 1}

###
PUT http://localhost:8080/transfer/external
Content-Type: application/json

{"idPlus": "bd047d20-9605-4568-ac06-c54d407f5901","idMinus": "3e2254f6-9cfe-4d7e-9da6-20a7d4e7d304","moneyChange": 100}



###
PUT http://localhost:8080/transfer/external
Content-Type: application/json

{"idPlus": "","idMinus": "","moneyChange": 1}
#######################
###
GET http://localhost:8081/accounts

###
POST http://localhost:8081/account
Content-Type: application/json

{"numberPhone": 2, "money": 2}





###
POST http://localhost:8080/account
Content-Type: application/json

{"numberPhone": 2, "money": 2}

###
POST http://localhost:8080/account
Content-Type: application/json

{"numberPhone": 3, "money": 3}

###
GET http://localhost:8080/account/delete/7741b38c-d962-4e16-ac49-53331f629085

###
PUT http://localhost:8080/account
Content-Type: application/json

{"id": "f7f5eaf1-4624-46ae-be9d-efd5327e3ddc","numberPhone": 11}

###
DELETE http://localhost:8080/account/f75a460c-3cc1-4531-8866-f8e0ac5d3c77

###
PUT http://localhost:8080/account/money/plus
Content-Type: application/json

{"id": "38bbb792-4a73-4b8b-81a8-0c9d9136659c","money": 1}

###
PUT http://localhost:8080/account/money/minus
Content-Type: application/json

{"id": "3e2254f6-9cfe-4d7e-9da6-20a7d4e7d304","money": 2}

###
PUT http://localhost:8080/transfer
Content-Type: application/json

{"idPlus": "38bbb792-4a73-4b8b-81a8-0c9d9136659c","idMinus": "1e9443f2-809a-4921-ae4e-a59732a17b36","moneyChange": 1}
