GET http://localhost:8080/accounts

###
POST http://localhost:8080/account
Content-Type: application/json

{"numberPhone": 1, "money": 1}

###
POST http://localhost:8080/account
Content-Type: application/json

{"numberPhone": 2, "money": 2}

###
POST http://localhost:8080/account
Content-Type: application/json

{"numberPhone": 3, "money": 3}

###
GET http://localhost:8080/account/f7f5eaf1-4624-46ae-be9d-efd5327e3ddc

###
PUT http://localhost:8080/account
Content-Type: application/json

{"id": "f7f5eaf1-4624-46ae-be9d-efd5327e3ddc","numberPhone": 11}

###
DELETE http://localhost:8080/account/f7f5eaf1-4624-46ae-be9d-efd5327e3ddc
