version: "3.1"

volumes:
  postgres_data_test: {}

networks:
  app:
    driver: bridge

# bd 1
services:
  db:
    image: postgres:15
    container_name: scala-postgres
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    networks:
      - app


  # bd 2
  # db_2:
  #   image: postgres:15
  #   container_name: scala-postgres-2
  #   env_file:
  #     - .env
  #   ports:
  #     - 5435:5432
  #   networks:
  #     - app

  # Сервис 1
  service_1:
    container_name: scala-service-1
    image: scala-service-1
    ports:
      - "8080:8080"
    build:
      context: ./
      dockerfile: ./docker/dockerfile
    networks:
      - app
# Сервис 2
# service_2:
#   container_name: scala-postgres-2
#   image: postgres:15
#   env_file:
#       - .env
#   ports:
#       - "8002:8001"
#   build:
#     context: ./
#     dockerfile: Dockerfile.service_2
#   networks:
#       - app
